[package]
name = "agglutinator"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[dependencies]
libc = "0.2.177"
nounwind = { version = "0.1.0", features = ["std"] }
strum = { version = "0.27.2", features = ["derive"] }
